auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
baseurl: /

title: BarretLee's Blog
url: barretlee.github.io
img_repo: http://qianduannotes.duapp.com/github/images
js_repo: http://qianduannotes.duapp.com/github/js
feed: /atom.xml
highlight: light
author_name: Barret Lee
author_info: <a href="http://barretlee.github.io">BarretLee</a>
