auto: true

markdown: rdiscount
pygments: true
paginate: 2
paginate_path: "blog/page:num"
permalink: /:title
baseurl: /

title: BarretLee's Blog
url: http://barretlee.github.io
repo: http://qianduannotes.duapp.com/github/barretlee.github.com
feed: /atom.xml
highlight: light
author_name: Barret Lee
author_info: <a href="http://barretlee.github.io">BarretLee</a>
