auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: BarretLee's Blog
url: barretlee.github.io
feed: /atom.xml
author_info: <a href="http://barretlee.github.io">BarretLee</a>
author.name: BarretLee
